### ISSUE TITLE
Export zaw-history

### ISSUE THREAD

**Issue by sorin-ionescu** [zsh-users/zaw#32]
I would like to see zaw-history exported out of zaw. It's the most useful part, and I suspect 99% of users just use that.

**Comment by willghatch** [comment]
It might make sense to split off the sources from the core, or allow users to either specify which of the default sources are included or which ones are excluded (though on my current machine loading all of zaw adds <10ms to my zsh load time, so I feel it would be a little moot to save ~2ms).  But as zaw-history depends on all the core zaw components, breaking it out into its own thing doesn't really make sense.

Personally, I think prezto would be just as well off including the whole thing if it will include a part (since that is the reason for this issue).  But then again I prefer package management via zgen over the frameworks such as prezto or oh-my-zsh.  So I may just have a different mindset in general.
