### ISSUE TITLE
Using current command line content as search term?

### ISSUE THREAD

**Issue by jfelchner** [zsh-users/zaw#49]
What I'd like to do is to be able to search backward through my history with the contents I may have already typed on the command line.

Is there a way to do this with zsh/zaw?

Currently if I enter zaw, after having already typed on the command line, I have to retype it in zaw.

Example:

    ssh someserver

Now I think, "What was that port again?" so I open zaw and I have to retype `ssh someserver` to find it.

**Comment by jkarni** [comment]
:+1: `zaw-history` is great, but the lack of this feature almost makes me want to go back to built-in zsh history commands

**Comment by jfelchner** [comment]
@willghatch I just tried your commit.  It's exactly what I was wanting :heart_eyes: 

THANK YOU SO MUCH!!

**Comment by moonrumble** [comment]
It is a good idea to extend this functionality to other sources like ssh-host etc

**Comment by willghatch** [comment]
I'm not sure it would be a great fit for ssh-host, because that probably implies that the line start `ssh`, but the hostnames probably don't have "ssh" in them, so you would have to go back and delete the ssh thing.  So unless you start adding some fancy filtering for what you want to keep from the initial command line (which I don't want to do), it wouldn't work very well.

**Comment by moonrumble** [comment]
Thanks, I was hoping that I can just type hostname and search using ssh-host source. Press enter.
